#!/usr/bin/env bash
#
# Bash script for provisioning MongoDB Enterprise environment on CentOS

set -e
set -x

function config_hosts(){
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_mongodb_enterprise(){
  echo "Install MongoDB Enterprise Repository"
  sudo echo "[mongodb-enterprise]
name=MongoDB Enterprise Repository
baseurl=https://repo.mongodb.com/yum/redhat/6/mongodb-enterprise/3.4/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.4.asc" > /etc/yum.repos.d/mongodb-enterprise.repo
  echo "Install EPEL repository"
  sudo yum install -y epel-release
  echo "Update Repositories"
  sudo yum update -y
  echo "Install MongoDB Enterprise"
  sudo yum install -y mongodb-enterprise
}

function install_python_deps(){
  sudo yum install -y python-devel
  sudo yum install -y python-pip
  sudo pip install pymongo
  sudo pip install docopt
  sudo pip install faker
  sudo pip install numpy
  sudo pip install mtools
}

function install_node_deps(){
  # workaround for missing nodejs packages
  sudo rpm -ivh https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
  sudo yum install -y npm
  npm install -g mongo-hacker
  ln -sf "/usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js" /home/vagrant/.mongorc.js
}

function config(){
  sudo su
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  # echo 'manual' | sudo tee /etc/init/mongod.override
  # add custom config for bashrc and vimrc
  echo "# Set prompt
PS1='[\u \W]\$ '

# User specific aliases and functions
alias ...='cd ../..'
alias ..='cd ..'
alias a='cd && clear'
alias c='clear'
alias grep='grep --color=auto'
alias h='history'
alias la='ls -la'
alias ll='ls -l'
alias p='python'
alias pm='ps -A | grep mongo'" >> /home/vagrant/.bashrc
  echo "set number
set ruler
set shiftwidth=4
set tabstop=4
syntax on
filetype indent plugin on" >> /home/vagrant/.vimrc
}

config_hosts
install_mongodb_enterprise
# installing node_deps currently breaks the VM build
# install_node_deps
install_python_deps
config
echo "DONE"
