#!/usr/bin/env bash
#
# Bash script for provisioning MongoDB Enterprise environment on OSX

set -e
set -x

function config_hosts(){
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_mongodb_enterprise(){
  echo "Download MongoDB Enterprise"
  curl -O https://downloads.mongodb.com/osx/mongodb-osx-x86_64-enterprise-3.4.7.tgz
  echo "Install MongoDB Enterprise"
  tar -zxvf mongodb-osx-x86_64-enterprise-3.4.7.tgz
  mkdir -p mongodb
  mv mongodb-osx-x86_64-enterprise-3.4.7/* mongodb
  mkdir -p /data/db
  rm -rf mongodb-osx-x86_64-enterprise-3.4.7.tgz mongodb-osx-x86_64-enterprise-3.4.7
}

function install_python_deps(){
  sudo apt-get install -y python-dev
  sudo apt-get install -y python-pip
  sudo pip install pymongo
  sudo pip install docopt
  sudo pip install faker
  sudo pip install numpy
  sudo pip install mtools
}

function install_node_deps(){
  sudo apt-get install -y npm
  npm install -g mongo-hacker
  ln -sf "/usr/local/lib/node_modules/mongo-hacker/mongo_hacker.js" /home/vagrant/.mongorc.js
}

function config(){
  echo "# Add mongo to the PATH
export PATH=/Users/vagrant/mongodb/bin:$PATH

# Set prompt
PS1='[\u \W]\$ '

# User specific aliases and functions
alias ...='cd ../..'
alias ..='cd ..'
alias a='cd && clear'
alias c='clear'
alias grep='grep --color=auto'
alias h='history'
alias la='ls -la'
alias ll='ls -l'
alias p='python'
alias pm='ps -A | grep mongo'" >> /Users/vagrant/.bashrc
  source /Users/vagrant/.bashrc
  echo "set number
set ruler
set shiftwidth=4
set tabstop=4
syntax on
filetype indent plugin on" >> /Users/vagrant/.vimrc
  sudo su
  # disable mongod upstart service
  # echo 'manual' | sudo tee /etc/init/mongod.override
  # add custom config for bashrc and vimrc
  chmod -R 777 /data
  chown -R vagrant /data
}

config_hosts
install_mongodb_enterprise
# install_node_deps
# install_python_deps
config
echo "DONE"
